trigger:
- main

pool:
  name: Default
  demands:
  - agent.name -equals test-deneme

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js'

- task: Npm@1
  displayName: 'npm install'
  inputs:
    verbose: false

- task: Npm@1
  displayName: 'npm run build'
  inputs:
    command: custom
    verbose: false
    customCommand: 'run build'

- script: |
    sonar-scanner.bat -D"sonar.projectKey=MobvenTeam1.FitAI-front-end-app-react.ts" -D"sonar.sources=." -D"sonar.host.url=http://localhost:9000" -D"sonar.token=sqp_996753382c228af14f30edb626a33c4e52752a01"
  displayName: 'SonarQube'

- task: SSH@0
  inputs:
    sshEndpoint: 'mobven-ssh'
    runOptions: 'commands'
    commands: |
      systemctl stop apache2

    readyTimeout: '20000'
  displayName: 'Service-Stop'

- task: CopyFilesOverSSH@0
  inputs:
    sshEndpoint: 'mobven-ssh'
    sourceFolder: '$(Pipeline.Workspace)/s/dist'
    contents: '**'
    targetFolder: '/var/www/FitAI/html'
    readyTimeout: '20000'
  displayName: 'CopyFilesOverSSH'

- task: SSH@0
  inputs:
    sshEndpoint: 'mobven-ssh'
    runOptions: 'commands'
    commands: |
      systemctl start apache2

    readyTimeout: '20000'
  displayName: 'Service-Start'